using FreshGuard.ColdTrack.Platform.Analytics.Application.OutboundServices;
using FreshGuard.ColdTrack.Platform.Analytics.Domain.Model.Aggregates;
using FreshGuard.ColdTrack.Platform.Analytics.Domain.Model.Entities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace FreshGuard.ColdTrack.Platform.Analytics.Infrastructure.Documents.QuestPdf;

public class PdfReportGenerator : IPdfReportGenerator
{
    public byte[] Generate(Report report, IReadOnlyCollection<HistoricalLog> history) => Document.Create(document =>
    {
        document.Page(page =>
        {
            page.Size(PageSizes.A4.Landscape());
            page.Margin(28);
            page.DefaultTextStyle(style => style.FontSize(9));
            page.Header().Column(column =>
            {
                column.Item().Text("ColdTrack Cold-Chain Report").FontSize(20).Bold().FontColor(Colors.Blue.Darken2);
                column.Item()
                    .Text($"{report.ReportCode} | {report.Period.Start:yyyy-MM-dd} to {report.Period.End:yyyy-MM-dd}");
            });
            page.Content().PaddingVertical(15).Column(column =>
            {
                column.Spacing(12);
                column.Item().Row(row =>
                {
                    Metric(row, "Completed shipments", report.CompletedShipments.ToString());
                    Metric(row, "Alerts", report.TotalAlerts.ToString());
                    Metric(row, "Average temperature", Format(report.AverageTemperature, " C"));
                    Metric(row, "Average humidity", Format(report.AverageHumidity, "%"));
                });
                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(1);
                        columns.RelativeColumn(1.4f);
                        columns.RelativeColumn(1.4f);
                        columns.RelativeColumn(1);
                        columns.RelativeColumn(1);
                        columns.RelativeColumn(1);
                        columns.RelativeColumn(.7f);
                    });
                    table.Header(header =>
                    {
                        Header(header, "Shipment");
                        Header(header, "Destination");
                        Header(header, "Driver");
                        Header(header, "Arrival");
                        Header(header, "Avg. temp.");
                        Header(header, "Avg. humidity");
                        Header(header, "Alerts");
                    });
                    foreach (var item in history)
                    {
                        Cell(table, item.ShipmentCode);
                        Cell(table, item.Destination);
                        Cell(table, item.DriverName);
                        Cell(table, item.ActualArrival?.ToString("yyyy-MM-dd HH:mm") ?? "-");
                        Cell(table, Format(item.AverageTemperature, " C"));
                        Cell(table, Format(item.AverageHumidity, "%"));
                        Cell(table, item.AlertCount.ToString());
                    }
                });
            });
            page.Footer().AlignCenter().Text(text =>
            {
                text.Span("Generated by ColdTrack | Page ");
                text.CurrentPageNumber();
                text.Span(" of ");
                text.TotalPages();
            });
        });
    }).GeneratePdf();

    private static void Metric(RowDescriptor row, string label, string value) => row.RelativeItem().Border(1)
        .BorderColor(Colors.Grey.Lighten2).Padding(8).Column(column =>
        {
            column.Item().Text(label).FontColor(Colors.Grey.Darken1);
            column.Item().Text(value).FontSize(14).Bold();
        });

    private static void Header(TableCellDescriptor header, string text) => header.Cell().Background(Colors.Blue.Darken2)
        .Padding(5).Text(text).FontColor(Colors.White).Bold();

    private static void Cell(TableDescriptor table, string text) => table.Cell().BorderBottom(1)
        .BorderColor(Colors.Grey.Lighten3).Padding(5).Text(text);

    private static string Format(decimal? value, string suffix) => value.HasValue ? $"{value:0.00}{suffix}" : "-";
}
